"""Auto-generate a module index for the calctoys src/ tree.

Walks src/, parses each .py with `ast` (no imports executed, so broken or
unusual-import modules are still indexed), and extracts top-level classes and
public functions plus any leading "Code reference" comments/docstrings. Emits
a Markdown table so references/ stays in sync with the code.

Usage:
    python index_modules.py                 # print to stdout
    python index_modules.py --write         # write references/module-index.generated.md
"""
from __future__ import annotations

import ast
import os
import sys

from pv_env import SRC  # noqa: E402  (SRC path constant; no calc imports)

_SKILL_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir))
_OUT = os.path.join(_SKILL_DIR, "references", "module-index.generated.md")


def _leading_reference(tree: ast.Module, source: str) -> str:
    """Best-effort one-line 'what Code is this' hint: the module docstring's
    first line, else the first top-of-file comment line."""
    doc = ast.get_docstring(tree)
    if doc:
        return doc.strip().splitlines()[0]
    for line in source.splitlines():
        s = line.strip()
        if s.startswith("#"):
            return s.lstrip("# ").strip()
        if s and not s.startswith(('"""', "'''")):
            break
    return ""


def _public_symbols(tree: ast.Module) -> tuple[list[str], list[str]]:
    classes, funcs = [], []
    for node in tree.body:
        if isinstance(node, ast.ClassDef):
            classes.append(node.name)
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            if not node.name.startswith("_"):
                funcs.append(node.name)
    return classes, funcs


def build_index() -> str:
    rows = []
    for dirpath, _dirs, files in os.walk(SRC):
        for fn in sorted(files):
            if not fn.endswith(".py") or fn == "__init__.py":
                continue
            full = os.path.join(dirpath, fn)
            rel = os.path.relpath(full, SRC)
            try:
                source = open(full, encoding="utf-8").read()
                tree = ast.parse(source)
            except (SyntaxError, OSError) as exc:
                rows.append((rel, "(parse error)", f"{type(exc).__name__}", ""))
                continue
            classes, funcs = _public_symbols(tree)
            if not classes and not funcs:
                continue
            ref = _leading_reference(tree, source)
            symbols = ", ".join(
                [f"`{c}`" for c in classes[:6]] + [f"`{f}()`" for f in funcs[:6]])
            extra = "" if (len(classes) <= 6 and len(funcs) <= 6) else " …"
            rows.append((rel, symbols + extra, ref, ""))

    rows.sort(key=lambda r: r[0])
    out = [
        "# Module index (generated)",
        "",
        "_Auto-generated by `scripts/index_modules.py`. Do not edit by hand._",
        "",
        f"Indexed {len(rows)} modules under `src/`.",
        "",
        "| Module (rel. to src/) | Public classes / functions | Reference |",
        "|---|---|---|",
    ]
    for rel, symbols, ref, _ in rows:
        ref_clean = ref.replace("|", "\\|")
        out.append(f"| `{rel}` | {symbols} | {ref_clean} |")
    return "\n".join(out) + "\n"


def main() -> int:
    text = build_index()
    if "--write" in sys.argv:
        with open(_OUT, "w", encoding="utf-8") as fh:
            fh.write(text)
        print(f"Wrote {_OUT}")
    else:
        print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
