"""Auto-generate a module index for the calctoys src/ tree.

Walks src/, parses each .py with `ast` (no imports executed, so broken or
unusual-import modules are still indexed), and extracts top-level classes and
public functions plus any leading "Code reference" comments/docstrings.

Usage:
    python index_modules.py            # print the flat index to stdout
    python index_modules.py --write    # write references/module-index.generated.md
    python index_modules.py --readme   # update the code index in the repo README.md
                                       #   (between the CODE-INDEX markers)
"""
from __future__ import annotations

import ast
import os
import sys

from pv_env import SRC, _REPO_ROOT  # noqa: E402  (path constants; no calc imports)

_SKILL_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir))
_OUT = os.path.join(_SKILL_DIR, "references", "module-index.generated.md")
_README = os.path.join(_REPO_ROOT, "README.md")

README_START = "<!-- CODE-INDEX:START (generated by scripts/index_modules.py --readme) -->"
README_END = "<!-- CODE-INDEX:END -->"

# Friendly titles for the top-level src/ packages, in display order.
_PACKAGE_TITLES = [
    ("Cylinder", "Cylindrical shells & formed heads"),
    ("Flange", "Bolted, clamped & metal-to-metal flanges"),
    ("Tubesheet", "Tubesheets (UHX / TEMA / Div 2)"),
    ("Noncircular", "Vessels of noncircular cross section (Appendix 13)"),
    ("Saddles", "Saddle supports (horizontal vessels)"),
    ("CombinedLoading", "Combined loading (wind / platform / lateral)"),
    ("ui", "Tkinter GUI"),
    ("", "Top-level / entry points"),
]


def _leading_reference(tree: ast.Module, source: str) -> str:
    """Best-effort one-line 'what Code is this' hint: the module docstring's
    first line, else the first top-of-file comment line."""
    doc = ast.get_docstring(tree)
    if doc:
        return doc.strip().splitlines()[0]
    for line in source.splitlines():
        s = line.strip()
        if s.startswith("#"):
            return s.lstrip("# ").strip()
        if s and not s.startswith(('"""', "'''")):
            break
    return ""


def _public_symbols(tree: ast.Module) -> tuple[list[str], list[str]]:
    classes, funcs = [], []
    for node in tree.body:
        if isinstance(node, ast.ClassDef):
            classes.append(node.name)
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            if not node.name.startswith("_"):
                funcs.append(node.name)
    return classes, funcs


def _collect_rows() -> list[tuple[str, str, str]]:
    """(rel_path, symbols_markdown, reference) for every non-empty module."""
    rows = []
    for dirpath, _dirs, files in os.walk(SRC):
        for fn in sorted(files):
            if not fn.endswith(".py") or fn == "__init__.py":
                continue
            full = os.path.join(dirpath, fn)
            rel = os.path.relpath(full, SRC).replace(os.sep, "/")
            try:
                source = open(full, encoding="utf-8").read()
                tree = ast.parse(source)
            except (SyntaxError, OSError) as exc:
                rows.append((rel, "(parse error)", f"{type(exc).__name__}"))
                continue
            classes, funcs = _public_symbols(tree)
            if not classes and not funcs:
                continue
            ref = _leading_reference(tree, source)
            symbols = ", ".join(
                [f"`{c}`" for c in classes[:6]] + [f"`{f}()`" for f in funcs[:6]])
            extra = "" if (len(classes) <= 6 and len(funcs) <= 6) else " …"
            rows.append((rel, symbols + extra, ref))
    rows.sort(key=lambda r: r[0])
    return rows


def build_index() -> str:
    rows = _collect_rows()
    out = [
        "# Module index (generated)",
        "",
        "_Auto-generated by `scripts/index_modules.py`. Do not edit by hand._",
        "",
        f"Indexed {len(rows)} modules under `src/`.",
        "",
        "| Module (rel. to src/) | Public classes / functions | Reference |",
        "|---|---|---|",
    ]
    for rel, symbols, ref in rows:
        ref_clean = ref.replace("|", "\\|")
        out.append(f"| `{rel}` | {symbols} | {ref_clean} |")
    return "\n".join(out) + "\n"


def build_readme_index() -> str:
    """Complete code index grouped by top-level package, for the README."""
    rows = _collect_rows()
    by_pkg: dict[str, list] = {}
    for rel, symbols, ref in rows:
        pkg = rel.split("/")[0] if "/" in rel else ""
        by_pkg.setdefault(pkg, []).append((rel, symbols, ref))

    out = [README_START,
           f"_{len(rows)} modules under `src/`. "
           "Auto-generated — run `python .claude/skills/pressure-vessel-design/"
           "scripts/index_modules.py --readme` to refresh._", ""]
    seen = set()
    titles = _PACKAGE_TITLES + [(p, p or "(root)") for p in sorted(by_pkg)
                                if p not in {k for k, _ in _PACKAGE_TITLES}]
    for pkg, title in titles:
        if pkg not in by_pkg or pkg in seen:
            continue
        seen.add(pkg)
        out.append(f"### {title}")
        out.append("")
        out.append("| Module | Public classes / functions | Reference |")
        out.append("|---|---|---|")
        for rel, symbols, ref in by_pkg[pkg]:
            ref_clean = ref.replace("|", "\\|")
            out.append(f"| `src/{rel}` | {symbols} | {ref_clean} |")
        out.append("")
    out.append(README_END)
    return "\n".join(out)


def _update_readme() -> int:
    with open(_README, encoding="utf-8") as fh:
        text = fh.read()
    block = build_readme_index()
    if README_START in text and README_END in text:
        pre = text[:text.index(README_START)]
        post = text[text.index(README_END) + len(README_END):]
        text = pre + block + post
    else:
        text = text.rstrip() + "\n\n## Complete code index\n\n" + block + "\n"
    with open(_README, "w", encoding="utf-8") as fh:
        fh.write(text)
    print(f"Updated code index in {_README}")
    return 0


def main() -> int:
    if "--readme" in sys.argv:
        return _update_readme()
    text = build_index()
    if "--write" in sys.argv:
        with open(_OUT, "w", encoding="utf-8") as fh:
            fh.write(text)
        print(f"Wrote {_OUT}")
    else:
        print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
